function adj = adjacents(loc)
%moore with center
[rows,cols] = size(loc);
[R,C] = meshgrid(1:rows,1:cols);
adj = ((circshift(loc,[0 -1]) & R<rows)...
        | (circshift(loc,[0 1]) & R>1)...
        | (circshift(loc,[-1 0]) & C<cols)...
        | (circshift(loc,[1 0]) & C>1))...
        & ~loc;
    
%         | (circshift(loc,[1 1]) & R>1 & C>1)...
%         | (circshift(loc,[-1 1]) & R<rows & C>1)...
%         | (circshift(loc,[1 -1]) & R>1 & C<cols)...
%         | (circshift(loc,[-1 -1]) & R<rows & C<cols))...